/* FORMULA SAE UFPB
 * DATA DE CRIAÇÃO:
 * CRIADO POR:
 * MANTIDO POR:
 * DESCRIÇÃO:
 * FUNÇÕES:
 * VERSÃO:
 */


void setup() {
  
  // CÓDIGO EXECUTADO APENAS UMA VEZ
  // CÓDIGO DE CONFIGURAÇÃO, BIBLIOTECAS E DECLARAÇÃO DE VARIÁVEIS
  

}

void loop() {
  // CÓDIGO QUE SERÁ EXECUTADO REPETIDAMENTE
  // ROTINAS DETERMINADAS PARA O ARDUINO

}
