/* FORMULA SAE UFPB
 * DATA DE CRIAÇÃO 04/08/2015
 * CRIADO POR: Josias Ferreira  
 * MANTIDO POR:
 * DESCRIÇÃO:
 * FUNÇÕES: Angulo dos três eixos;
 * VERSÃO:0.1
 */


void setup() {
  
  // CÓDIGO EXECUTADO APENAS UMA VEZ
  // CÓDIGO DE CONFIGURAÇÃO, BIBLIOTECAS E DECLARAÇÃO DE VARIÁVEIS
  

}

void loop() {
  // CÓDIGO QUE SERÁ EXECUTADO REPETIDAMENTE
  // ROTINAS DETERMINADAS PARA O ARDUINO

}
